apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-chain-config
  namespace: k8s-tutorial
data:
  # Format: service-name.namespace.svc.cluster.local
  REVERSE_PROXY_URL: "http://reverse-proxy-service:3002"
  BACKEND_URL: "http://backend-service:3003"
