apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-chain-config
  namespace: k8s-tutorial
data:
  # Internal K8s DNS: service-name.namespace.svc.cluster.local
  REVERSE_PROXY_URL: "http://reverse-proxy-service.k8s-tutorial.svc.cluster.local:3002"
  BACKEND_URL: "http://backend-service.k8s-tutorial.svc.cluster.local:3003"