apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: k8s-tutorial
  annotations:
    # This tells Google Cloud to create a standard external Load Balancer
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      # Traffic to /api-proxy/ goes to the Forward Proxy
      - path: /api-proxy
        pathType: Prefix
        backend:
          service:
            name: forward-proxy-service
            port:
              number: 3001
      # Everything else (the UI) goes to the SPA
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spa-service
            port:
              number: 80